export default WalletTransactionLogType = {
    DEPOSIT: 1,
    WITHDRAW: 2,
    TRANSFER_IN: 3,
    TRANSFER_OUT: 4,
    BONUS_ON_USER_SALE: 5,
    BONUS_ON_GROUP_MEMBER_SALE: 6,
    SOMEONE_BUY_YOUR_PRODUCT: 7,
    YOU_BUY_PRODUCT: 8,
    YOU_CANCELED_ORDER: 9,
    YOUR_ORDER_HAS_BEEN_CANCELED: 10,
    CHANGED_BY_ADMIN: 11,
    RETURN_BONUS_USER_CANCEL_ODER_ADMIN: 15,
    RETURN_BONUS_USER_CANCEL_ODER_ADMIN_GROUP: 16
}